### PR TITLE
adding detail information about scanned annotations

### PR DESCRIPTION
**Pull request by Grummfy**
Adapt #58 as asked

### CODE REVIEW

**Comment by tshafer** [comment]
Tests?

**Comment by tshafer** [comment]
Please provide a output of what this does. How is it beneficial?

**Comment by Grummfy** [comment]
I was explain in the PR #58...  the purpose is to help people extending this libs if they need

**Comment by tshafer** [comment]
Please provide tests

**Comment by Grummfy** [comment]
Here it is, I added the same kind of test.

**Comment by Grummfy** [comment]
thanks

**Comment by Grummfy** [comment]
Is it possible to add to the next release of 5.6 branch?

**Pull request merged**
