### PR TITLE
Laravel 5.7 support

### LINKED ISSUE #78: please  release 5.7
please  release 5.7

### PR DESCRIPTION
**Pull request by johntimothybailey**
Provides support for Laravel 5.7

I do not *really* want this to be a PR against `5.6` branch. However, not sure how to request creation of a new branch `5.7` on this main repo and opening it against `master` confused what changed since master is not matching `5.6`

Closes #78

### CODE REVIEW

**Comment by stamp** [comment]
Hey @adamgoose and @mlantz (saw your names in the LaravelCollective organization)

Could you or the correct maintainer for this repo take a look at this PR?

Thanks a lot! :)

**Comment by loonytoons** [comment]
Thanks @johntimothybailey. I made one more update to the composer file (for the branch alias), but have hit a weird issue with the tests in trying to get the master branch inline with the release branches.
Once that's sorted we can get the 5.7 tag released, and look to sorting 5.8

**Comment by loonytoons** [comment]
FYI this change has been merged into the new 5.7 branch. As soon as the tests fix has been merged into that branch, I'll close the 5.7 issue and create the tag.

I'll close this MR now though, as it's already merged into the other branch

**Comment by loonytoons** [comment]
FYI 5.7 tag has now been created

**Pull request closed without merging**
