### PR TITLE
Allow use attribute instead of annotation

### PR DESCRIPTION
**Pull request by ggg-mzkr**
Allow use attribute instead of annotation.

## Implementation design
1. Separate the existing`AnnotationScanner` into the base scanner and annotation-dependent parts as ScanStrategy. And check pass the existing tests.
2. Create an`AttributeScanStrategy` and test that the scan results are the same as the `AnnotationScanStrategy`.
3. Make `AnnotationsServiceProvider` to allow to switch strategies.

### ex)
Annotation
```php
 /**
   * @Get("login")
   * @Middleware("guest")
   */
  public function login()
  {
    return view('index');
  }
```
Attribute
```php
  #[Get(path: 'login')]
  #[Middleware(name: 'guest')]
  public function login()
  {
    return view('index');
  }
```

If use attribute, set `$useAttribute` to`true`  in`AnnotationsServiceProvider.php`;

```php
<?php namespace App\Providers;

use Collective\Annotations\AnnotationsServiceProvider as ServiceProvider;

class AnnotationsServiceProvider extends ServiceProvider {

.....
.....

    /**
     * Determines whether to use attributes for scanning.
     *
     * @var bool
     */
    protected $useAttribute = false;

.....
.....
}
```

### CODE REVIEW

**Comment by ggg-mzkr** [comment]
I Organized the commit history from the previous PR.

https://github.com/LaravelCollective/annotations/pull/116

**Comment by loonytoons** [comment]
Thanks @ggg-mzkr, lots of tidy up stuff here! And nice one implementing the php 8 specificity for the attributes.

One question, for someone to migrate from annotations to attributes, is it expected that they'll need to add the use statements for the various attribute classes being used? It doesn't seem obvious from the readme that these would also need to be added. It'll only trip up people migrating, and only because they'll be used to not needing to include them due to the autoloading done in the background. Not saying ones right or wrong, just noting the difference.

@szeber would you mind taking a look at this, seeing as you looked at the previous iteration?

**Comment by loonytoons** [comment]
@ggg-mzkr thanks for your patience. I was hoping to get a second pair of eyes across this, but it's proving tricky. I'll get this sorted this week though!

**Review by loonytoons — APPROVED** [review]

**Comment by loonytoons** [comment]
Looks like travis ci has finally been disconnected, and I don't have the perms to change how the tests run. So just noting that I've run them all manually for php 7.3, 7.4 and 8.0

**Comment by loonytoons** [comment]
@ggg-mzkr I finally got there! Thanks for your patience, and thanks so much for your contribution! 🙌

**Pull request merged**
