### PR TITLE
upgrade requirement for laravel 5.1 support.

### LINKED ISSUE #32: Laravel 5.1 support?
I see `laravelcollective/html` is already supporting 5.1 but annotations is not, is there a major blocking point preventing support currently?

### PR DESCRIPTION
**Pull request by gravitano**
Fix #32.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by gravitano** [comment]
why?

**Comment by GrahamCampbell** [comment]
This isn't correct and is sent to the wrong branch anyway.

**Comment by gravitano** [comment]
Hey, Laravel 5.1 require symfony component version `~2.7` right? I've tried install this package to my Laravel 5.1 project and its fail and cannot installed. Which branch should I send this pull request? 

Sorry for my bad English :)

**Comment by GrahamCampbell** [comment]
But you've broken 5.0 support on the 5.0 branch which is incorrect.

**Comment by jonathanpmartins** [comment]
@gravitano, that was just an example to solve the incompatibility problem rapidly.

**Pull request closed without merging**
